### ISSUE TITLE
Errors when testing newly installed genipe: TypeError: __init__() got an unexpected keyword argument 'normalize'

### ISSUE THREAD

**Issue by ashaked** [pgxcentre/genipe#52] opened 2017-11-30 14:41 UTC
Hi,
I have uninstalled pandas to 0.20 to fix the other issue, and this is what have been installed:
(genipe_pyvenv) [bl@node107 ~]$ pip list
biopython (1.70)
cycler (0.10.0)
drmaa (0.7.8)
genipe (1.3.3)
Jinja2 (2.10)
lifelines (0.12.0)
MarkupSafe (1.0)
matplotlib (2.1.0)
numpy (1.13.3)
pandas (0.20.0)
patsy (0.4.1)
pip (1.5.6)
pyfaidx (0.5.1)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.3)
scipy (1.0.0)
setuptools (38.2.3)
six (1.11.0)
statsmodels (0.8.0)

>>> import genipe
>>> genipe.test()
/opt/software/python/3.4.2/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return f(*args, **kwds)
........................................................................................................ss.s....EEEEEERROR:root:Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

ERROR:root:__init__() got an unexpected keyword argument 'normalize'
E[2017-11-30 09:11:57 ERROR] Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

[2017-11-30 09:11:57 ERROR] __init__() got an unexpected keyword argument 'normalize'
E[2017-11-30 09:11:58 ERROR] multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 880, in compute_statistics
    for result in pool.map(process_impute2_site, sites_to_process):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'normalize'

[2017-11-30 09:11:58 ERROR] __init__() got an unexpected keyword argument 'normalize'
E..........................[2017-11-30 09:16:04 WARNING] interaction term is categorical: the last category will be used in the results
[2017-11-30 09:16:04 WARNING] when using interaction, mixedlm optimization cannot be performed, analysis will be slow
.[2017-11-30 09:17:05 WARNING] interaction term is categorical: the last category will be used in the results
[2017-11-30 09:17:05 WARNING] when using interaction, mixedlm optimization cannot be performed, analysis will be slow
....ssssss..ss/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/pipeline/cli.py:2516: MatplotlibDeprecationWarning: The *bottom* kwarg to `barh` is deprecated use *y* instead. Support for *bottom* will be removed in Matplotlib 3.0
  align="center")
...s.s.........
======================================================================
ERROR: test_fit_cox_interaction_snp1 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function with interaction, first SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 866, in test_fit_cox_interaction_snp1
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_fit_cox_invalid (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_linear' function, third SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 832, in test_fit_cox_invalid
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_fit_cox_snp1 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, first SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 730, in test_fit_cox_snp1
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_fit_cox_snp2 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, second SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 767, in test_fit_cox_snp2
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_fit_cox_snp3 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, third SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 803, in test_fit_cox_snp3
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_full_fit_cox (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 893, in test_full_fit_cox
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_full_fit_cox_interaction (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression with interaction.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 1071, in test_full_fit_cox_interaction
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'

======================================================================
ERROR: test_full_fit_cox_multiprocess (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression with >1 processes.
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1133, in fit_cox
    cf = CoxPHFitter(alpha=0.95, tie_method="Efron", normalize=False)
TypeError: __init__() got an unexpected keyword argument 'normalize'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 983, in test_full_fit_cox_multiprocess
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 880, in compute_statistics
    for result in pool.map(process_impute2_site, sites_to_process):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'normalize'

----------------------------------------------------------------------
Ran 176 tests in 568.242s

FAILED (errors=8, skipped=13)

**Comment by lemieuxl** [comment] 2017-11-30 14:58
Duplicate of #41 
Duplicate of #44 
We are working on releasing a new version of *genipe* which is compatible with the newest versions of *pandas* and *lifelines*. In the meantime, you can downgrade to *pandas* version 0.19 and *lifelines* version 0.9.

**Comment by ashaked** [comment] 2017-11-30 15:51
Thank you! I downgraded lifelines to 0.9, but new errors occurred:
>>> genipe.test()
/opt/software/python/3.4.2/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return f(*args, **kwds)
........................................................................................................ss.s....EEEEEERROR:root:Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

ERROR:root:'DataFrame' object has no attribute 'sort'
E[2017-11-30 10:21:10 ERROR] Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

[2017-11-30 10:21:10 ERROR] 'DataFrame' object has no attribute 'sort'
E[2017-11-30 10:21:11 ERROR] multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 880, in compute_statistics
    for result in pool.map(process_impute2_site, sites_to_process):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
AttributeError: 'DataFrame' object has no attribute 'sort'

[2017-11-30 10:21:11 ERROR] 'DataFrame' object has no attribute 'sort'
E..........................[2017-11-30 10:25:13 WARNING] interaction term is categorical: the last category will be used in the results
[2017-11-30 10:25:13 WARNING] when using interaction, mixedlm optimization cannot be performed, analysis will be slow
.[2017-11-30 10:26:13 WARNING] interaction term is categorical: the last category will be used in the results
[2017-11-30 10:26:13 WARNING] when using interaction, mixedlm optimization cannot be performed, analysis will be slow
....ssssss..ss/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/pipeline/cli.py:2516: MatplotlibDeprecationWarning: The *bottom* kwarg to `barh` is deprecated use *y* instead. Support for *bottom* will be removed in Matplotlib 3.0
  align="center")
...s.s.........
======================================================================
ERROR: test_fit_cox_interaction_snp1 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function with interaction, first SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 866, in test_fit_cox_interaction_snp1
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_fit_cox_invalid (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_linear' function, third SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 832, in test_fit_cox_invalid
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_fit_cox_snp1 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, first SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 730, in test_fit_cox_snp1
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_fit_cox_snp2 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, second SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 767, in test_fit_cox_snp2
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_fit_cox_snp3 (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the 'fit_cox' function, third SNP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 803, in test_fit_cox_snp3
    formula=formula,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_full_fit_cox (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 893, in test_full_fit_cox
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_full_fit_cox_interaction (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression with interaction.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 1071, in test_full_fit_cox_interaction
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 877, in compute_statistics
    print(*process_impute2_site(site), sep="\t", file=o_file)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

======================================================================
ERROR: test_full_fit_cox_multiprocess (genipe.tests.test_imputed_stats.TestImputedStatsCox)
Tests the full pipeline for Cox's regression with >1 processes.
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1034, in process_impute2_site
    interaction=site_info.inter_c is not None,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 1134, in fit_cox
    cf.fit(data, duration_col=time_to_event, event_col=event)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/lifelines/fitters/coxph_fitter.py", line 285, in fit
    df.sort(duration_col, inplace=True)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tests/test_imputed_stats.py", line 983, in test_full_fit_cox_multiprocess
    imputed_stats.main(args=options)
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 163, in main
    options=args,
  File "/home/baoli/genipe_pyvenv/lib/python3.4/site-packages/genipe/tools/imputed_stats.py", line 880, in compute_statistics
    for result in pool.map(process_impute2_site, sites_to_process):
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/software/python/3.4.2/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
AttributeError: 'DataFrame' object has no attribute 'sort'

----------------------------------------------------------------------
Ran 176 tests in 562.637s

FAILED (errors=8, skipped=13)
>>>

**Comment by lemieuxl** [comment] 2017-11-30 15:56
Did you downgrade *pandas* to 0.19?

**Comment by ashaked** [comment] 2017-11-30 18:37
Yes, I just did (the 2nd downgrade of the day :) and there's no error message this time. Thank you!

**Comment by lemieuxl** [comment] 2017-11-30 18:46
We will release *genipe* version 1.4.0 pretty soon. With this version, you'll be able to upgrade all the modules to their most recent version.

**Closed by lemieuxl** 2017-11-30 18:46 UTC
